#ifndef _DRIVE_HPP_
#define _DRIVE_HPP_

#define LEFTMOTOR1PORT 1
#define LEFTMOTOR2PORT 5
#define LEFTMOTOR3PORT 2
#define RIGHTMOTOR1PORT 3
#define RIGHTMOTOR2PORT 6
#define RIGHTMOTOR3PORT 4

#define IMUPORT 15
#define VERTICALENCODERPORT 20
#define HORIZONTALENCODERPORT 14

extern lemlib::Chassis chassis;

#endif